<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-28J8ISPE" ignored="0" name="Default test" tests="5" failures="1" timestamp="14 三月 2018 07:21:14 GMT" time="1.598" errors="0">
  <testcase name="loginFail1" time="1.145" classname="com.edu.login.loginTest">
    <failure type="java.lang.Exception" message="expectedValue doesn&amp;apos;t match actualValue,actual Value is :200; expected Value is :400">
      <![CDATA[java.lang.Exception: expectedValue doesn't match actualValue,actual Value is :200; expected Value is :400
at com.apitest.check.util.Checker.verify(Checker.java:60)
at com.apitest.check.util.Checker.verifyXpath(Checker.java:44)
at com.edu.login.loginTest.loginFail1(loginTest.java:36)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- loginFail1 -->
  <testcase name="loginFail2" time="0.104" classname="com.edu.login.loginTest"/>
  <testcase name="loginFail3" time="0.098" classname="com.edu.login.loginTest"/>
  <testcase name="loginFail4" time="0.09" classname="com.edu.login.loginTest"/>
  <testcase name="loginSuccess" time="0.113" classname="com.edu.login.loginTest"/>
</testsuite> <!-- Default test -->
